services:
  tf_serving:
    image: tensorflow/serving:2.18.0  # ใช้ TensorFlow Serving version ที่ต้องการ  # ถ้ายังไม่มี image Docker จะดึง image นี้จาก Docker Hub
    ports:
      - "8601:8601"  # เปิดพอร์ตสำหรับ REST API
    volumes:
      - ./models:/models  # โฟลเดอร์ที่เก็บโมเดลจากเครื่อง host ไปยัง container
    command:
      - "tensorflow_model_server"
      - "--rest_api_port=8601"  # เปิดพอร์ต REST API ที่ 8601
      - "--model_config_file=/models/models.config"
    restart: always
